version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./instance:/app/instance
      - ./backups:/app/backups
      - ./migrations:/app/migrations
    env_file:
      - .env
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static:ro
    depends_on:
      - web
    restart: unless-stopped
