version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 "app:create_app()"
    volumes:
      - .:/app
      - ./instance:/app/instance
      - ./migrations:/app/migrations
      - ./app/static:/app/static
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////app/instance/app.db
      - TZ=${TZ:-UTC}
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/usr/share/nginx/html/static:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d:rw
    depends_on:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
